name: 👾 Bug report
description: Report an issue with Comicers
labels: [bug]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Before opening a ticket, please go through the following steps.
      options:
        - label: Ensure that Comicers is up-to-date (check the About tab).
          required: true
        - label: Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
          required: true
        - label: If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/TheFizFactor/Comicers-App-extensions/issues/new/choose) instead.
          required: true
        - label: Write a concise title for this ticket in the field above.
          required: true

  - type: input
    id: comicers-version
    attributes:
      label: Comicers version
      description: |
        Your Comicers version is listed in the "About" tab.
      placeholder: |
        Example: "2.4.0"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
      placeholder: |
        Example: "Windows 10, macOS 11.5.2"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue occurs
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example: "It should have said..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example: "It actually said..."
    validations:
      required: true

  - type: textarea
    id: log-files
    attributes:
      label: Log files
      description: |
        Uploading your log files will help diagnose the issue.
      placeholder: |
        Attach your client log files:
          - Windows: C:/Users/you/AppData/Roaming/Comicers/logs
          - Mac: ~/Library/Application Support/Comicers/logs
          - Linux: $XDG_CONFIG_HOME/Comicers/logs OR ~/.config/Comicers/logs
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information (optional)
